ARG CONTAINER_IMAGE_REGISTRY

FROM ${CONTAINER_IMAGE_REGISTRY:+${CONTAINER_IMAGE_REGISTRY}/}alpine:3.21.3

RUN \
  apk add --update --no-cache \
  go=1.23.7-r0

ARG CONTAINER_USER=default
ARG CONTAINER_USER_GROUP=default

RUN addgroup -S ${CONTAINER_USER_GROUP} \
  && adduser -S ${CONTAINER_USER} -G ${CONTAINER_USER_GROUP}

USER ${CONTAINER_USER}:${CONTAINER_USER_GROUP}

VOLUME [ "/var/workspace" ]

WORKDIR /var/workspace

ONBUILD ARG SOURCE_DIR

ONBUILD COPY ${SOURCE_DIR} ${SOURCE_DIR}

ONBUILD ARG BINARY_OUTPUT_PATH

ONBUILD RUN \
  WORKDIR=$(pwd);\
  cd ${SOURCE_DIR}\
  && go build -o ${BINARY_OUTPUT_PATH} *.go
