services:
  builder:
    build:
      context: .
      dockerfile: builder.Dockerfile
    image: go-builder
  grm:
    build:
      args:
        BUILDER_CONTAINER_IMAGE: go-builder
      context: .
      dockerfile: grm.Dockerfile
    depends_on:
      - builder
    volumes:
      - .:/var/workspace:rw
  terminal:
    build:
      context: .
      dockerfile: terminal.Dockerfile
    volumes:
      - .:/var/workspace:rw
